# Uncomment the next line to define a global platform for your project
# platform :ios, '8.0'

target 'iOSLearnigDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for iOSLearnigDemo
  pod 'Masonry','1.1.0'
  pod 'CYLTabBarController','1.17.14'
  pod 'SDWebImage','4.4.2'
  pod 'SDWebImage/GIF'
  pod 'SDWebImage/WebP'
  pod 'YYModel','1.0.4'
  pod 'FDFullscreenPopGesture', '1.1'
  pod 'AFNetworking', '3.2.1'
  
  pod 'JTCalendar', '2.2.3'
  pod 'FSCalendar', '2.7.9'
  pod 'KVOController'
#  pod 'WeexSDK', '0.12.0'
  pod 'JSPatch','1.1.3'
end
